apiVersion: v1
kind: Service
metadata:
  name: my-index-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-index-app
  ports:
    - protocol: TCP
      port: 3000        # external port exposed by the LoadBalancer
      targetPort: 3000  # container port your app listens on
