name: Deploy to Amazon EKS

on:
  workflow_dispatch: 
#  push:
#   branches: [ "main" ]

env:
  AWS_REGION: us-east-2                               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: harikrishnan/my-devops-repo         # set this to your Amazon ECR repository name
#  ECS_SERVICE: gha-node-app                           # set this to your Amazon ECS service name
#  ECS_CLUSTER: My-DEVOPS-Cluster                      # set this to your Amazon ECS cluster name
#  ECS_TASK_DEFINITION: task-definition.json           # set this to the path to your Amazon ECS task definition
                                                      # file, e.g. .aws/task-definition.json
#  CONTAINER_NAME: gha-node-app
# ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
#  SUBNETS: subnet-0ae4c8dd3afdfcf2f,subnet-0a889ecc0a7248cc6  
#  SECURITY_GROUP: sg-0cf539d1bcf5b46d9                # set this to the name of the container in the
                                                      # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
#    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
       
        docker build . --file dockop --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT

    - name: Replace Image in Manifest
      run: |
        IMAGE_URI=675344694125.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

        sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8-deployment.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8-deployment.yaml
        kubectl apply -f k8-Service.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/my-index-app
