name: Build and Push to ECR

on:
 # push:
#  branches: [ "main" ]
#  pull_request:
#   branches: [ "main" ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: self-hosted
    env:
     ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true


    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file FirstImage --tag "${{ secrets.DOCKER_USERNAME }}"/nodeapp:${{ github.sha }}

      - name: Push the Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/nodeapp:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2   # change to your region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

#      - name: Pull image from Docker Hub
#       run: docker pull "${{ secrets.DOCKER_USERNAME }}"/my-image-name:${{ github.sha }}

      - name: Tag image for ECR
        run: |
         docker tag "${{ secrets.DOCKER_USERNAME }}"/nodeapp:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/harikrishnan/my-devops-repo:${{ github.sha }}

      - name: Push image to ECR
        run: |
         docker push ${{ steps.login-ecr.outputs.registry }}/harikrishnan/my-devops-repo:${{ github.sha }}  
